const {verifySignedIn,consumeAiBudget}=require('../lib/haneul-security');
const YT_ID=/^[A-Za-z0-9_-]{6,20}$/;
function hangulRatio(s=''){const h=(String(s).match(/[가-힣]/g)||[]).length,l=(String(s).match(/[A-Za-z가-힣]/g)||[]).length;return l?h/l:0}
function decode(s=''){return String(s).replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'")}
function extractJsonArray(html,key){const k=html.indexOf(key);if(k<0)return null;const st=html.indexOf('[',k+key.length);if(st<0)return null;let d=0,q=false,e=false;for(let i=st;i<html.length;i++){const c=html[i];if(q){if(e)e=false;else if(c==='\\')e=true;else if(c==='"')q=false;continue}if(c==='"'){q=true;continue}if(c==='[')d++;else if(c===']'&&--d===0)return html.slice(st,i+1)}return null}
function splitTimedText(text,startMs,endMs){const parts=String(text||'').replace(/\n+/g,' ').trim().split(/\s+/).filter(Boolean);if(!parts.length)return[];const span=Math.max(1,endMs-startMs),weights=parts.map(w=>Math.max(1,(w.match(/[가-힣A-Za-z0-9]/g)||[]).length)),sum=weights.reduce((a,b)=>a+b,0);let acc=0;return parts.map((word,i)=>{const ws=startMs+span*(acc/sum);acc+=weights[i];const we=startMs+span*(acc/sum);return{word,startMs:Math.round(ws),endMs:Math.max(Math.round(ws)+40,Math.round(we))}})}
function parseJson3(data){const out=[];for(const x of data?.events||[]){const segs=x.segs||[],text=decode(segs.map(s=>s.utf8||'').join('').replace(/\n+/g,' ').replace(/\s+/g,' ').trim());if(!text||x.tStartMs==null)continue;const startMs=Number(x.tStartMs),duration=Math.max(250,Number(x.dDurationMs||1800)),endMs=startMs+duration,words=[];for(let i=0;i<segs.length;i++){const raw=decode(String(segs[i]?.utf8||'').replace(/\n+/g,' ').replace(/\s+/g,' ').trim());if(!raw)continue;const off=Number(segs[i]?.tOffsetMs||0),nextOff=i+1<segs.length?Number(segs[i+1]?.tOffsetMs||duration):duration,ws=Math.max(startMs,startMs+off),we=Math.min(endMs,Math.max(ws+40,startMs+nextOff));words.push(...splitTimedText(raw,ws,we))}out.push({startMs,endMs,ko:text,en:'',...(words.length?{words}: {})})}return out}
async function provider(videoId,req){
 // Provider tokens are billable: unauthenticated requests are allowed to use
 // YouTube's public captions fallback but may not consume this private key.
 const signed=await verifySignedIn(req);
 if(!signed.ok){const e=new Error('signed_in_provider_required');e.code='signed_in_provider_required';throw e}
 if(!await consumeAiBudget(signed.token,'caption')){
  const e=new Error('caption_provider_rate_limit');e.code='caption_provider_rate_limit';throw e;
 }
 const u=new URL('https://api.freetranscriptapi.com/v1/transcript');u.searchParams.set('video_url',videoId);u.searchParams.set('lang','ko');const headers={accept:'application/json'};if(process.env.FTA_API_KEY)headers.authorization='Bearer '+process.env.FTA_API_KEY;const r=await fetch(u,{headers,signal:AbortSignal.timeout(18000)});if(r.status===429){const err=new Error('rate_limit_exceeded');err.code='rate_limit_exceeded';throw err}if(!r.ok){const err=new Error('provider_'+r.status);err.code='provider_error';throw err}const d=await r.json();const rows=Array.isArray(d.transcript)?d.transcript:[];const cues=rows.map(x=>{const startMs=Math.max(0,Math.round(Number(x.start||0)*1000)),dur=Math.max(250,Math.round(Number(x.duration||1.8)*1000)),endMs=startMs+dur,rawWords=Array.isArray(x.words)?x.words:[],words=rawWords.map(w=>{const rawStart=w.startMs??w.start_ms??w.start,rawEnd=w.endMs??w.end_ms??w.end;let ws=Number(rawStart),we=Number(rawEnd);if(!Number.isFinite(ws)||!Number.isFinite(we))return null;if(ws<10000&&we<10000){ws*=1000;we*=1000}return{word:String(w.word??w.text??'').trim(),startMs:Math.round(ws),endMs:Math.round(we)}}).filter(w=>w&&w.word&&w.endMs>w.startMs);return{startMs,endMs,ko:String(x.text||'').trim(),en:'',...(words.length?{words}: {})}}).filter(x=>x.ko);const sample=cues.slice(0,100).map(x=>x.ko).join(' ');if(!cues.length||hangulRatio(sample)<.45)return{ok:false,reason:'provider-no-korean-track',cues:[]};return{ok:true,videoId,language:d.language||'ko',title:d.title||'',source:'provider-freetranscriptapi',autoGenerated:false,translated:false,cues}}
async function youtube(videoId){const w=await fetch('https://www.youtube.com/watch?v='+encodeURIComponent(videoId)+'&hl=ko',{signal:AbortSignal.timeout(15000),headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36','accept-language':'ko-KR,ko;q=0.9,en;q=0.6'}});if(!w.ok)throw new Error('youtube_'+w.status);const html=await w.text(),raw=extractJsonArray(html,'"captionTracks":');if(!raw)return{ok:false,reason:'no-caption-track',cues:[]};let tracks;try{tracks=JSON.parse(raw)}catch{return{ok:false,reason:'caption-metadata-unreadable',cues:[]}}const ko=tracks.find(t=>t.languageCode==='ko'&&t.kind!=='asr')||tracks.find(t=>t.languageCode==='ko')||tracks.find(t=>String(t.languageCode||'').startsWith('ko'));if(!ko?.baseUrl)return{ok:false,reason:'no-korean-caption-track',available:tracks.map(t=>t.languageCode),cues:[]};const u=new URL(ko.baseUrl);u.searchParams.set('fmt','json3');const r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0'}});if(!r.ok)throw new Error('caption_'+r.status);const cues=parseJson3(await r.json());const sample=cues.slice(0,100).map(x=>x.ko).join(' ');if(!cues.length||hangulRatio(sample)<.45)return{ok:false,reason:'youtube-track-not-korean',cues:[]};return{ok:true,videoId,language:ko.languageCode||'ko',trackName:ko.name?.simpleText||'Korean',source:'youtube-caption-fallback',autoGenerated:ko.kind==='asr',translated:false,cues}}

function normalizeReviewCues(raw){
  const noise=/^\s*(?:\[(?:음악|박수|웃음|music|applause)[^\]]*\]|\((?:음악|박수|웃음|music|applause)[^)]*\)|[0-9\s]+|[으어음아]+)\s*$/i;
  const cleaned=[];
  for(const cue of raw||[]){
    const ko=String(cue.ko||'').replace(/\s+/g,' ').trim();
    if(!/[가-힣]/.test(ko)||noise.test(ko))continue;
    const start=Number(cue.startMs),end=Number(cue.endMs);
    if(!Number.isFinite(start)||!Number.isFinite(end)||end-start<120)continue;
    const previous=cleaned[cleaned.length-1];
    if(previous&&previous.ko===ko&&Math.abs(previous.startMs-start)<200)continue;
    cleaned.push({...cue,ko,startMs:Math.max(0,Math.round(start)),endMs:Math.round(end)});
  }
  cleaned.sort((a,b)=>a.startMs-b.startMs);
  for(let i=0;i+1<cleaned.length;i++){
    const current=cleaned[i],next=cleaned[i+1];
    if(current.endMs>next.startMs&&next.startMs-current.startMs>=160){
      current.endMs=Math.max(current.startMs+120,next.startMs-12);
      if(Array.isArray(current.words))current.words=current.words.map(w=>({...w,endMs:Math.min(Number(w.endMs),current.endMs)})).filter(w=>w.endMs>w.startMs);
    }
  }
  return cleaned;
}
function reviewTranscript(data,videoId){
  if(!data.ok)return data;
  if(data.language&&String(data.language).toLowerCase()!=='ko'&&!String(data.language).toLowerCase().startsWith('ko-'))return{ok:false,videoId,reason:'transcript-language-mismatch',cues:[]};
  const cues=normalizeReviewCues(data.cues),sample=cues.slice(0,100).map(c=>c.ko).join(' ');
  if(cues.length<12||hangulRatio(sample)<.65)return{ok:false,videoId,reason:'korean-transcript-needs-repair',cues:[]};
  return{...data,cues,reviewNormalized:true,wordTimingEstimated:cues.some(c=>!Array.isArray(c.words)||!c.words.length)}
}
module.exports=async function(req,res){res.setHeader('Access-Control-Allow-Origin','*');const u=new URL(req.url||'/','https://haneul.local'),videoId=String(u.searchParams.get('videoId')||''),source=String(u.searchParams.get('source')||''),review=u.searchParams.get('review')==='1';if(!YT_ID.test(videoId))return res.status(400).json({ok:false,error:'Invalid video id',cues:[]});try{let data;if(source==='youtube'){data=await youtube(videoId)}else if(source==='provider'){data=await provider(videoId,req)}else if(videoId==='Eo2I6voTVnA'){try{data=await youtube(videoId);if(!data.ok)throw new Error(data.reason||'youtube_unusable')}catch(e){data=await provider(videoId,req)}}else{try{data=await provider(videoId,req)}catch(e){data=await youtube(videoId)}}if(review){data=reviewTranscript(data,videoId);if(!data.ok&&source!=='provider'&&source!=='youtube'){try{const fallback=reviewTranscript(await youtube(videoId),videoId);if(fallback.ok)data=fallback}catch{}}}if(data.ok)res.setHeader('Cache-Control','public, s-maxage=86400, stale-while-revalidate=604800');else res.setHeader('Cache-Control','public, s-maxage=300, stale-while-revalidate=900');return res.status(200).json(data)}catch(e){res.setHeader('Cache-Control','no-store');return res.status(e.code==='signed_in_provider_required'?401:e.code==='caption_provider_rate_limit'?429:502).json({ok:false,error:e.code==='signed_in_provider_required'?'Sign in to use this transcript provider':e.code==='caption_provider_rate_limit'?'Transcript provider limit reached. Try YouTube captions or retry later.':'caption_fetch_failed',cues:[]})}};